name: Monitor X Followers

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch: # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps chromium

      - name: Try to download previous data
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: monitor-followers.yml
          name: x-followers-data
          path: .
          if_no_artifact_found: warn
          search_artifacts: true
        continue-on-error: true

      - name: Run followers monitor
        run: python main.py
        env:
          X_COOKIES: ${{ secrets.X_COOKIES }}
          X_USERNAME: ${{ secrets.X_USERNAME }}

      - name: Upload followers data
        uses: actions/upload-artifact@v4
        with:
          name: x-followers-data
          path: |
            followers_data.json
            followers_history/
          retention-days: 90
          overwrite: true
